config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'
  resources :lists, only: %i[index show new create] do
    resources :bookmarks, only: %i[new create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :list, uniqueness: { scope: :movie }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
    @bookmark.list = @list
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy

    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show]

  def index
    @lists = List.all
  end

  def show
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to lists_path
    else
      render :new
    end
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= asset_path('auditorium.jpg') %>')">
  <div class="container d-flex align-items-center flex-column">
    <h1>New movie bookmark</h1>
    <p>Choose a movie and leave a comment</p>
  </div>
</div>

<div class="container w-50">
  <%= simple_form_for [@list, @bookmark], defaults: { input_html: { class: 'form-group' } } do |f| %>
    <%= f.association :movie%>
    <%= f.input :comment %>
    <%= f.button :submit, class: 'btn btn-primary'  %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src="https://kit.fontawesome.com/1a577a62e6.js" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "cinema_icon.png", class: "avatar" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <%= link_to "My lists", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "New list", new_list_path, class: "nav-link" %>
          </li>
      </ul>
    </div>
  </div>
</div>

app/views/lists/index.html.erb
<%= render "navbar" %>

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= asset_path('auditorium.jpg') %>')">
  <div class="container d-flex align-items-center flex-column">
    <h1>Awesome movie lists</h1>
    <p>Classic</p>
  </div>
</div>


<div class="container d-flex justify-content-between mt-5 mb-3 align-items-baseline">
  <h1>My Lists</h1>
  <%= link_to new_list_path, class: "btn btn-flat my-3" do%>
    <i class="fa-solid fa-plus"></i> Create a movie list
  <% end%>
</div>


 <div class="container">
  <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4 g-4 mt-3">
      <% @lists.each do |list| %>
        <div class="col mb-3">
          <% img_url = list.photo.attached? ? cl_image_path(list.photo.key, height: 300, crop: :fill) : asset_path('film-roll.jpg') %>
          <div class="card-list" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= img_url %>')">
            <%= link_to list.name, list_path(list), class: "stretched-link" %>
          </div>
        </div>
      <% end%>
  </div>
</div>

app/views/lists/new.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= asset_path('auditorium.jpg') %>')">
  <div class="container d-flex align-items-center flex-column">
    <h1>New list</h1>
    <p>Choose a name and upload a picture for your list</p>
  </div>
</div>

<div class="container w-50">
  <%= simple_form_for @list, defaults: { input_html: { class: 'form-group' } } do |f| %>
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
    <%= f.button :submit, class: 'btn btn-primary'  %>
  <% end %>
</div>

app/views/lists/show.html.erb
<%= render "navbar" %>

<% img_url = @list.photo.attached? ? cl_image_path(@list.photo.key, height: 300, crop: :fill) : asset_path('film-roll.jpg') %>
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= img_url %>')">
  <div class="container d-flex align-items-center flex-column">
    <h1><%= @list.name %></h1>
  </div>
</div>

<div class="container d-flex justify-content-between align-items-baseline mt-5 mb-3">
  <%= link_to new_list_bookmark_path(@list), class:"btn btn-flat" do%>
    <i class="fa-solid fa-plus"></i> add a movie
  <% end %>
  <%= link_to root_path, class:"btn btn-flat" do%>
    <i class="fa-solid fa-rotate-left"></i> Back
  <% end %>
</div>

<div class="container">
  <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4 g-4">
    <% @list.movies.each do |movie| %>
      <% bookmark = Bookmark.find_by(movie: movie, list: @list) %>
       <div class="col">
        <div class="card-movie">
          <img src=<%= movie.poster_url %> alt=<%= movie.title %>/>
          <div class="card-body">
            <h5 class="card-title card-movie-title-font">
              <%= movie.title %> <small class="text-muted">&#8226; 8.5 <i class="fa fa-star card-movie-star" aria-hidden="true"></i></small>
            </h5>
            <p class="card-text card-movie-text-font"><%= movie.overview %></p>
          </div>
          <div class="card-movie-footer">
            <div class="card-movie-comment-font"><i class="fa-solid fa-quote-left"></i> <%= bookmark.comment %></div>
            <%= link_to "delete", bookmark_path(bookmark), method: :delete, data: { confirm: "Are you sure?" }, class: "text-danger" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>